### ISSUE TITLE
found some problem here

### ISSUE THREAD

**Issue by Samthapa76** [cleolibrary/CLEO5#140]
i see here some problem for me 

i use  

call  @Load 0

instead this 0ab1:

0ab1: @Load 0

and

ret 0

instead 

0ab2: 0

just for this cleo5 ends my most scripts

and that red error text too small to read

**Comment by MiranDMC** [comment]
If you created your own mode where cleo_call is renamed to call I do not see why this should not work anymore.
Same with 0AB2

Screen traces size can be configured in cleo\cleo_plugins\SA.DebugUtils.ini

**Comment by x87** [comment]
closing as inactive
