### ISSUE TITLE
Create Weapon Pickups mod seemingly incompatible with latest Cleo version

### ISSUE THREAD

**Issue by Maxtron01** [cleolibrary/CLEO5#141]
An error message pops up saying the script is suspended before launching into the actual game.

**Comment by x87** [comment]
@Maxtron01 Can you share a link to the mod, and a screenshot of the error?

**Comment by Maxtron01** [comment]
Here you go:

link to the site: Create Weapon Pick-Ups by Editing a Data File - MixMods
<https://www.mixmods.com.br/2018/04/criar-pick-ups-de-armas-editando-um-arquivo-dat/>

**Comment by Maxtron01** [comment]
And here's the error message in case you couldn't see it from my email: 
![Screenshot 2024-06-01 155105](https://github.com/cleolibrary/CLEO5/assets/115789743/53ad3252-b685-499d-a272-ba2f521cdbe3)

**Comment by x87** [comment]
@Maxtron01 did you copy mod files in CLEO folder, or you use modloader with custom folder? if latter, please try installing in CLEO folder.

**Comment by Maxtron01** [comment]
I have moved all files over to the Cleo folder from the modloader folder.
No error message popped up. Seems to be fixed now.

**Comment by x87** [comment]
@MiranDMC that script tries to load a file using "CLEO\file.ext" filepath. Is this not working from modloader?

**Comment by MiranDMC** [comment]
Mod Loader makes multiple hack on cleo and other asi plugins and it seems to struggle in new situation.
 Some preparations are already taken to introduce actual ML support without the hacks.

**Comment by MiranDMC** [comment]
Fixed in PR, but seems that mod has bunch of other problems. It tries to deallocate invalid memory pointer.
Tested it on CLEO 4.4.4 and 4.4.3, and it only spawns single pickup, despite 3 declared in the .dat file.

**Comment by x87** [comment]
@Maxtron01 try latest alpha.70 build and see if there are still issues with the mod

**Comment by MiranDMC** [comment]
Partially fixed, rest of the problems occur even in CLEO4. This mod is not well made.
