### ISSUE TITLE
UDS:Trojan.Win32.Yephiller.Bok

### ISSUE THREAD

**Issue by Daru00** [cleolibrary/CLEO5#142]
Well cleo 5 is being detected as a trojan so can't be used.

**Comment by x87** [comment]
These virus reports are a joke. They flag even an empty DLL.

If you don't trust a pre-built version, build CLEO from source code using VS 2022, see how our CI [does it](https://github.com/cleolibrary/CLEO5/blob/master/.github/workflows/main.yml#L31-L33).

**Comment by x87** [comment]
https://www.virustotal.com/gui/file/af97f9683846a5c0199029b5abd606b88d4f1afb69cc83a3befd2a2ae3f95f7a?nocache=1
[Dll1.zip](https://github.com/user-attachments/files/15539734/Dll1.zip)

3 AVs flag the code below, find any trojan in it:

```
// dllmain.cpp : Defines the entry point for the DLL application.
#include "pch.h"

#pragma once
#pragma warning(disable:4733)
#define _USE_MATH_DEFINES
#define WIN32_LEAN_AND_MEAN
#undef UNICODE

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <memory>
#include <assert.h>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <direct.h>
#include <list>
#include <vector>
#include <set>
#include <cstdint>




BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

```

**Comment by Daru00** [comment]
using kaspersky,avg,avira,clamav, and lastly avast all of them detect cleo as the one mentioned.
And that code is quite known so normally isn't flagged by anything at all unless someone put a trojan on them.
![002](https://github.com/cleolibrary/CLEO5/assets/137091871/6d10efba-43c2-4eb2-b613-5c5c48febb0a)

**Comment by MiranDMC** [comment]
It was not like that before, and code was not touched since then. Even locally build dll gives same results. Virus Total returns several false picks, where half of them ale bullshit names like 'genericX' or straight 'suspicious'. We need to take look at is, as for example CLEO4 has no problems while contains very similar set of features.

**Comment by MiranDMC** [comment]
@CanerKaraca23  Make sure you are doing tests on current code, or even better on https://github.com/cleolibrary/CLEO5/tree/malware_fixes_3 branch.
What version exactly did you use? We will probably select explicit version for automatic builds to avoid problem where Gihub update build environment and things start to act differently.

**Comment by MiranDMC** [comment]
> Used latest version, not exactly a specific versions like old.

Yes, but the it uses some specific version you have installed locally.

**Comment by MiranDMC** [comment]
Fixed in alpha 63
