### ISSUE TITLE
problem with ImVehFt & GFXHack

### ISSUE THREAD

**Issue by answerix-core** [cleolibrary/CLEO5#148]
all the other essential plugins are working properly, patches, asi plugins, mods, everything. except for GFXHack and Improved Vehicle Features. Soon as I install those, the .exe file launches after giving GFXHacl error Code: 988 if I'm not mistaken; then crashes when having loaded the game completely on Loading Screen. I have already tried reinstalling my game, Deleting the User Files, changing when I install either of those mods, etc. But the game still refuses to run properlly when having any of these two mods installed with CLEO V.5 Alpha.

thanks in advance.

**Comment by niresh1234** [comment]
Is working without GFXHack?

**Comment by x87** [comment]
@answerix-core do you still have the issue? does it work if you install CLEO 4?

**Comment by MiranDMC** [comment]
I tested SkyGFX recently and it works. GFXHack seems to start correct if not placed in ModLoader folder.
As @CanerKaraca23 mentioned vehicle features mod also works ok.
