### ISSUE TITLE
[suggestion] cmd

### ISSUE THREAD

**Issue by D3Pheonix** [cleolibrary/CLEO5#151]
Hi, can u add in-game debug console, like in SAMPFUNCS ?

**Comment by MiranDMC** [comment]
What does it mean? There are already features for printing debug messages from scripts.
https://library.sannybuilder.com/#/sa/classes/Debugger
See for example `trace` https://library.sannybuilder.com/#/sa/debug/2101

**Comment by D3Pheonix** [comment]
![image](https://github.com/cleolibrary/CLEO5/assets/60894481/54e105ea-b121-4ba6-a6d6-53fea4cce9ae)

**Comment by x87** [comment]
CLEO Redux (JS) can execute any command (opcode) from a text file in real time

**Comment by MiranDMC** [comment]
It would not be difficult to write something like that as cs script. This looks like ImGUI, which is available for regular CLEO too.
Generally sounds like stand alone project that does not have to be build into CLEO.
