### ISSUE TITLE
0AA2 load_dynamic_library does not work

### ISSUE THREAD

**Issue by Aldrin-John-Olaer-Manalansan** [cleolibrary/CLEO5#177]
I have a script that uses foreign functions from MSIAPI. They are working properly on Cleo 4.4.1, but after I migrated to Cleo 5 then this error message shows up:
![image](https://github.com/user-attachments/assets/21c52de0-9620-4652-8304-ab55b946c72c)

I have come up with a very simple test script that only tries to execute Opcode 0AA2 with conditions:
* Use Clean GTA No Other Mods
* Use Silent Asi Loader and Cleo 5 only.
* Test Script: [testings.zip](https://github.com/user-attachments/files/16645830/testings.zip)

```
{$CLEO}
0000:

if 8AA2: not 0@ = load_dynamic_library "Kernel32.dll"
then 0A93: terminate_this_custom_script
end

0A93: terminate_this_custom_script
```

Sanny builder 3 correctly decompiles it:
```
{$CLEO .cs}

0000: NOP
00D6: if 
8AA2:   not "Kernel32.dll" = load_dynamic_library 0@ // IF and SET
004D: jump_if_false @Noname_34
0A93: terminate_this_custom_script

:Noname_34
0A93: terminate_this_custom_script

```
and Sanny builder 4 as well correctly decompiles it:
```
{$CLEO .cs}

0000: nop 
00D6: if 
8AA2:   not load_dynamic_library {fileName} 0@ {var_handle} "Kernel32.dll"
004D: goto_if_false @Noname_34
0A93: terminate_this_custom_script 

:Noname_34
0A93: terminate_this_custom_script 
```
So I'm sure that Cleo 5 has the issue.

Take note that I **didn't use** any **DLL Procs** for this test because I find it unecessary to test as well, since the failure happens when the DLL gets loaded. 

Using this cleo script, Error message pops up, while ingame a red error message overlay is at the top of the screen.

Single Player:
![image](https://github.com/user-attachments/assets/57b58cce-5d12-4a08-aa15-9df44481d002)

SAMP
![image](https://github.com/user-attachments/assets/86255238-8d3d-4dcd-b00b-66c89b7bdb31)

This confirms that opcode 0AA2 doesn't work the way it should be. Or maybe I'm using it wrong?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> I have a script that uses foreign functions from MSIAPI. They are working properly on Cleo 4.4.1, but after I migrated to Cleo 5 then this error message shows up: ![image](https://private-user-images.githubusercontent.com/39627255/358860739-21c52de0-9620-4652-8304-ab55b946c72c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTkxMTgsIm5iZiI6MTcyMzkxODgxOCwicGF0aCI6Ii8zOTYyNzI1NS8zNTg4NjA3MzktMjFjNTJkZTAtOTYyMC00NjUyLTgzMDQtYWI1NWI5NDZjNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4MjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2UxZDZhNGZkNWMxNGQ3ZjAyMTM3YzgwMDY4OWNjMDE4ZWQ0YzM4YjEyZmI2MDdlMTY1MDFlZTQ0OTY5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aRf7g6_ZaQolWfzPvseJRYTQpIYSPHFce0qnt6F0S20)
> 
> I have come up with a very simple test script that only tries to execute Opcode 0AA2 with conditions:
> 
> * Use Clean GTA No Other Mods
> * Use Silent Asi Loader and Cleo 5 only.
> * Test Script: [testings.zip](https://github.com/user-attachments/files/16645830/testings.zip)
> 
> ```
> {$CLEO}
> 0000:
> 
> if 8AA2: not 0@ = load_dynamic_library "Kernel32.dll"
> then 0A93: terminate_this_custom_script
> end
> 
> 0A93: terminate_this_custom_script
> ```
> 
> Sanny builder 3 correctly decompiles it:
> 
> ```
> {$CLEO .cs}
> 
> 0000: NOP
> 00D6: if 
> 8AA2:   not "Kernel32.dll" = load_dynamic_library 0@ // IF and SET
> 004D: jump_if_false @Noname_34
> 0A93: terminate_this_custom_script
> 
> :Noname_34
> 0A93: terminate_this_custom_script
> ```
> 
> and Sanny builder 4 as well correctly decompiles it:
> 
> ```
> {$CLEO .cs}
> 
> 0000: nop 
> 00D6: if 
> 8AA2:   not load_dynamic_library {fileName} 0@ {var_handle} "Kernel32.dll"
> 004D: goto_if_false @Noname_34
> 0A93: terminate_this_custom_script 
> 
> :Noname_34
> 0A93: terminate_this_custom_script 
> ```
> 
> So I'm sure that Cleo 5 has the issue.
> 
> Take note that I **didn't use** any **DLL Procs** for this test because I find it unecessary to test as well, since the failure happens when the DLL gets loaded.
> 
> Using this cleo script, Error message pops up, while ingame a red error message overlay is at the top of the screen.
> 
> Single Player: ![image](https://private-user-images.githubusercontent.com/39627255/358861580-57b58cce-5d12-4a08-aa15-9df44481d002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTkxMTgsIm5iZiI6MTcyMzkxODgxOCwicGF0aCI6Ii8zOTYyNzI1NS8zNTg4NjE1ODAtNTdiNThjY2UtNWQxMi00YTA4LWFhMTUtOWRmNDQ0ODFkMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4MjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkM2Y2YTRiYmE5YWMyODY5OGVkOWI4MmNlNDc2ODUwOTRlNWE5YTJiOTFhYzU5MDg4ZjljMDI3ZmNiMmNmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RsvSK0dqpNs28pqH1CZc7YqjZDIUmJHhfytD0Y8Ipvg)
> 
> SAMP ![image](https://private-user-images.githubusercontent.com/39627255/358861470-86255238-8d3d-4dcd-b00b-66c89b7bdb31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTkxMTgsIm5iZiI6MTcyMzkxODgxOCwicGF0aCI6Ii8zOTYyNzI1NS8zNTg4NjE0NzAtODYyNTUyMzgtOGQzZC00ZGNkLWIwMGItNjZjODliN2JkYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE4MjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MmZlNTI4NDdhMDFiN2M1OGVmNWI3M2ExZmMyMDg5NTdjYjMzOTU4ZDIyYzc1ZGY0NGJkNTkzYWIzYjcyZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A80llbGGicthyKAPwuuocxl8w6s84g6drI0i5gDrhAY)
> 
> This confirms that opcode 0AA2 doesn't work the way it should be. Or maybe I'm using it wrong?

I take it back 🤦 , Sanny builder 4 messed up the arrangement of the opcodes, wtf?

**Comment by x87** [comment]
In new SBL modes all opcodes have their arguments in the original conventional order: all inputs first, outputs after. 0AA2 had their params re-ordered in legacy SA 1.0 mode.

Quick solution: don't use opcode syntax in new SBL mode. Sanny will correctly arrange params in all commands:

```
{$CLEO}
nop

if not 0@ = load_dynamic_library "Kernel32.dll"
then terminate_this_custom_script
end

terminate_this_custom_script
```

**Comment by MiranDMC** [comment]
Yep, error message clearly informs you that input parameters is invalid. Decompiled code shows you switched arguments around.
This script is not working in CLEO4 too, but it just fails in silence. I'm surprised it is not crashing, but it would anyway if the (not)loaded library was put to use later.
