### ISSUE TITLE
PUA:Win32/GameHack

### ISSUE THREAD

**Issue by PUAyomom** [cleolibrary/CLEO5#179]
every damn time i try to unzip CLEO5 for gta san andreas windows security nags me about PUA:Win32/GameHack how do i stop windows security from nagging me every fucking time i unzip the damn zip for CLEO5

**Comment by MiranDMC** [comment]
Add exception for that file in your AV. 
This is GameHack after all. 
PUA stands for Potentially Unwanted Application.

**Comment by PUAyomom** [comment]
oh thx

**Comment by PUAyomom** [comment]
oh thx i will do it
