### ISSUE TITLE
RZL-Trainer Version for San Andreas?

### ISSUE THREAD

**Issue by enessmr** [cleolibrary/CLEO5#181]
Hi. I am playing this game for months with the older version of CLEO. And I updated it today. Now RZL Trainer does not work. Help ME! I have some severe mods too. Like SAXVCXLC

**Comment by enessmr** [comment]
![{7C54650F-D7FE-49C1-8713-A9C228717C0E}](https://github.com/user-attachments/assets/a17c124f-20e9-4128-ab17-37492ac62163)
Proof

**Comment by MiranDMC** [comment]
Rename trainer file extension to .cs4

**Comment by enessmr** [comment]
worked

**Comment by enessmr** [comment]
I did get the error message. And i renamed it.
