### ISSUE TITLE
not working !!

### ISSUE THREAD

**Issue by mouad23annabi** [cleolibrary/CLEO5#188]
whene i start the game cant find tag cleo in menu and in the game mods not working !! need help

**Comment by MiranDMC** [comment]
Make sure you downloaded correct version including ASI loader, like this one:
https://github.com/cleolibrary/CLEO5/releases/download/v5.0.0-alpha.69/SA.CLEO_v5.0.0-alpha.69+Silent_ASI_Loader.zip

**Comment by x87** [comment]
closing. please open a new ticket if you have another issue

latest build and installation instructions can be found here
https://github.com/cleolibrary/CLEO5/releases
