### ISSUE TITLE
Errors after new alpha release

### ISSUE THREAD

**Issue by CanerKaraca23** [cleolibrary/CLEO5#189]
I get these error after new alpha release, don't have any issue with previous version.

![Ekran görüntüsü 2024-09-13 025327](https://github.com/user-attachments/assets/f2158d65-06b0-49b7-8b67-99145278677a)
![Ekran görüntüsü 2024-09-13 025335](https://github.com/user-attachments/assets/5254040c-ba16-4648-bf7d-69bc3f8140b5)
![Ekran görüntüsü 2024-09-13 025342](https://github.com/user-attachments/assets/93dbd013-af4f-4d78-bce7-9d6bc393a275)
![Ekran görüntüsü 2024-09-13 025349](https://github.com/user-attachments/assets/27c03d1f-f66e-4519-b56e-310972a10979)

**Comment by MiranDMC** [comment]
What version exactly it is? I was unable to reproduce in 68 and current master (69).
```

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 What version exactly it is? I was unable to reproduce in 68 and current master (69).
> 
> ```
> {$CLEO .cs}
> nop
> 
> create_directory {dirName} "user:\test_dir"
> write_int_to_ini_file {value} 42 {path} "user:\test_dir\test_file.ini" {section} "section" {key} "key"
> 
> terminate_this_script
> ```

Alpha 68 is fine but 69 is broken for me and looks like 69 is rolled back from releases.

**Comment by x87** [comment]
@CanerKaraca23 try with https://github.com/cleolibrary/CLEO5/actions/runs/10851396101/artifacts/1930350978

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 try with https://github.com/cleolibrary/CLEO5/actions/runs/10851396101/artifacts/1930350978

Works fine, thanks.
