### ISSUE TITLE
SAMP FXT Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [cleolibrary/CLEO5#194]
Hi,

Some cleo mods like [Stream Usage Counter](https://www.mixmods.com.br/2015/01/stream-usage-counter-mostrar-o-uso-de-memoria-do-jogo/) gives error when playing SA-MP.

There is a [mod](https://www.mixmods.com.br/2016/08/samp-fxt-fix-corrigir-mods-fxt-no-samp/) that fixes this error but, why we need a seperate mod that fix an issue?

Can i request a fix from CLEO itself? So we don't have to use this.

Error:
![sa-mp-000](https://github.com/user-attachments/assets/78471ff5-454f-4cf3-98b2-b39bca3d1432)

**Comment by Samthapa76** [comment]
O.O man samp has totally different story go to https://ugbase.eu/ ask help there its nothing to do with cleo 5 
i did coding for 5 years for samp i know samp actually don't allow cleo but people keep forcing it now r4 and r4 very strict about cleo

**Comment by CanerKaraca23** [comment]
> go to https://ugbase.eu/ ask help there its nothing to do with cleo 5 i did coding for 5 years for samp i know samp actually don't allow cleo but people keep forcing it now r4 and r5 very strict about cleo

I know, i mean, implement this fix in CLEO itself.

**Comment by MiranDMC** [comment]
Whenever CLEO install hooks it usually assumes call could be hooked already by someone else and try to act transparent by latter calling the found code instead what is known to be in original game.

In this case CLEO is replacing some code and then somebody else is overwriting that modification later. Even if CLEO wait to be the last one who makes the change there is no generic solution how the existing hook should be executed after finishing CLEO's hook.

This needs tailored solution for exactly that situation, and mentioned mod does exactly that. Is that's fix mod source code even available somewhere to see?

**Comment by CanerKaraca23** [comment]
> Whenever CLEO install hooks it usually assumes call could be hooked already by someone else and try to act transparent by latter calling the found code instead what is known to be in original game.
> 
> In this case CLEO is replacing some code and then somebody else is overwriting that modification later. Even if CLEO wait to be the last one who makes the change there is no generic solution how the existing hook should be executed after finishing CLEO's hook.
> 
> This needs tailored solution for exactly that situation, and mentioned mod does exactly that. Is that's fix mod source code even available somewhere to see?

I didn't see anywhere but i guess we can request from Fabio3.

https://github.com/Fabio3rs

**Comment by Fabio3rs** [comment]
If I remember correctly, it is this code: https://github.com/Fabio3rs/SAMP-fxt-fix/blob/main/paynspray/main.cpp

This fix operates waiting the address change and re-hooking it.

**Comment by MiranDMC** [comment]
So it just reinstall CLEO's hook? Why SAMP hacks it in the first place? Don't the fix then kill some SAMP's text related feature?

**Comment by Fabio3rs** [comment]
> So it just reinstall CLEO's hook? Why SAMP hacks it in the first place? Don't the fix then kill some SAMP's text related feature?

SAMP uses to print its own texts, the code collects the CLEO and SAMP's function pointer, then it install its own pointer. It has a function that calls one of the functions, check if the text is found, if not, it calls the other pointer.

**Comment by MiranDMC** [comment]
Ok, so you implemented proper fix.

I do not think that should be part of CLEO. Going by that logic it would need to constantly monitor all it's hooks in case somebody modify them.

Additionally as mentioned SAMP is doing active efforts to prevent CLEO use and I don't thing we should actively counteract that in any way.

**Comment by CanerKaraca23** [comment]
> Ok, so you implemented proper fix.
> 
> I do not think this should be part of CLEO. Going by that logic it would need to constantly monitor all it's hooks in case somebody modify them. Even when detected there is no generic way to solve conflicts like that.
> 
> Additionally as mentioned SAMP is doing active efforts to prevent CLEO use and I don't think we should actively counteract that in any way.

Okay then, I get it, thanks. Anyway, do you think this code needs update/change/refactor or is it still good to go?

You can close the issue if you want.

**Comment by MiranDMC** [comment]
Ok thanks for report and efforts.
From @Fabio3rs description it sounds like solid solution. Code looked fine when I took brief look too.
Why it is internally named PayNSpray is only puzzling thing.

**Comment by Fabio3rs** [comment]
> Ok thanks for report and efforts. From @Fabio3rs description it sounds like solid solution. Code looked fine when I took brief look too. Why it is internally named PayNSpray is only puzzling thing.

Thanks.
At the time I was creating the project, I was duplicating the directory from the PayNSpray color picker and using the preconfigured project as base for newer projects haha

I thought about renaming before uploading today, but if I did the visual studio project would break.
