### ISSUE TITLE
Stuck in black screen when exiting 

### ISSUE THREAD

**Issue by Meyers07** [cleolibrary/CLEO5#228]
I'm installing CLEO5, directly overwriting CLEO4 files (haven't touched GTA SA since 2 years ago) no problems but every time i exit game:
- the menu screen stuck in black screen - the cleo version and plugin stuck in the bottom left.
- task manager shows gta_sa.exe is running (not "Not Responding"), can be end tasked.
Is this problem with older plugins or CLEO5 itself?

I try delete some CLEO cs scripts i installed at the same time, still happened,
I deleted CLEO5 files and installed back CLEO4 files (but i install CLEO 4.4.4, previously i use CLEO 4.4.0), FIXED, game exits as normal.

**Comment by Meyers07** [comment]
It may be connected to this issue
https://github.com/thelink2012/modloader/issues/114

**Comment by MiranDMC** [comment]
ModLoader causes BASS library to hang when Cleo tries to release it. Already fixed, waits for build.
Version can be already tested there:
https://github.com/cleolibrary/CLEO5/actions/runs/11192990074

**Comment by MiranDMC** [comment]
Fixed in Alpha.75
