### ISSUE TITLE
mods that include custom audio dont work with cleo 5 rc1

### ISSUE THREAD

**Issue by skelebone208** [cleolibrary/CLEO5#253]
ive switched from cleo 4 to cleo 5 and im currently modifying gta san andreas when i came into an issue. specific cleo mods that add their own custom sounds dont play the audio correctly or dont play the audio at all. an example of this is the Void's Weapon Wheel mod. please provide me a solution if possible.

**Comment by x87** [comment]
Please provide link to the mod and Cleo log

**Comment by Jessyy** [comment]
Hello all,

I've also switched to v5 ( from v4 ), on my side I can not reproduce this issue.
By default the mod has the audio part disabled - VoidWeaponWheel.ini:
```
EnableSounds = 0 #Enable the sound effects, you can replace or delete any of the sound files on the audio folder of this mod. Default 0
```
@skelebone208 can you confirm that on your side is set to 1 as well ?

> Please provide link to the mod and Cleo log
You can get the latest version ( v1.3 at the time of this comment ) from here - https://libertycity.net/files/gta-san-andreas/211490-void-weapon-wheel.html

**Comment by MiranDMC** [comment]
Works for me too. As mentioned sounds are disabled by default in the mod's settings file.
