### ISSUE TITLE
Mod Not Working

### ISSUE THREAD

**Issue by CanerKaraca23** [cleolibrary/CLEO5#26]
This mod is not working on CLEO 5, tested on alpha 25.

https://www.mixmods.com.br/2018/01/elm-emergency-lights-mod-v1-0-by-nyolc8/

**Comment by CanerKaraca23** [comment]
@x87 @MiranDMC can you release new alpha so i can test?

**Comment by MiranDMC** [comment]
We still have some issues to fix. This mod has at least one not critical error, which causes warning messages to print on screen in new CLEO.

**Comment by MiranDMC** [comment]
@CanerKaraca23 
5.0.0-alpha.27 is out. Rename your script to *.cs4 to suppress warning messages from not critical script errors.

**Comment by CanerKaraca23** [comment]
> @CanerKaraca23 5.0.0-alpha.27 is out. Rename your script to *.cs4 to suppress warning messages from not critical script errors.

Thanks. First, mod worked well without renaming it to .cs4 but i got 70mb log file lol. Then i renamed both two .cs files to .cs4, no problem, still have some errors like you said not critical on .log file but not 70mb this time. Anyway, i will ask some questions. This mod require NewOpcodes.cleo. In CLEO 5, plugin directory changed and probably regular users will download mods that require CLEO+ and NewOpcodes.cleo from mod websites and move it to cleo folder instead of cleo_plugins, so they will get error because plugin missing. Also regular users needs to rename their old mods to .cs4 manually as i understand.

![Ekran görüntüsü 2023-11-12 220900](https://github.com/cleolibrary/CLEO5/assets/37447503/c3611e46-c68a-4dad-9df7-b460116a62d4)

**Comment by x87** [comment]
CLEO5 supports .cleo plugins from new AND old location. there should not be a missing plugin error.

You don't need to rename all scripts to .cs4, it's only for certain mods that have known issues. Ideally, they should be updated to fix their mistakes, but for some unmaintained scripts there is the compatibility mode.

**Comment by CanerKaraca23** [comment]
> CLEO5 supports .cleo plugins from new AND old location. there should not be a missing plugin error.
> 
> You don't need to rename all scripts to .cs4, it's only for certain mods that have known issues. Ideally, they should be updated to fix their mistakes, but for some unmaintained scripts there is the compatibility mode.

Thanks for the answer, then there is no problem left then. Almost all of my cleo mods are not maintained anymore.

**Comment by MiranDMC** [comment]
> > @CanerKaraca23
> ![Ekran görüntüsü 2023-11-12 220900](https://user-images.githubusercontent.com/37447503/282320339-c3611e46-c68a-4dad-9df7-b460116a62d4.png)
These (starting scrip) log messages were present in previous CLEO too.
