### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CanerKaraca23** [cleolibrary/CLEO5#58]
![Ekran görüntüsü 2024-02-13 195612](https://github.com/cleolibrary/CLEO5/assets/37447503/988040c5-793f-48db-ac14-eaadb8829737)

Got this error even in compatibility mode.

Log: [cleo.log](https://github.com/cleolibrary/CLEO5/files/14269771/cleo.log)

Version: alpha.33

Mod: https://www.mixmods.com.br/2018/07/saas-san-andreas-ambient-sounds/

**Comment by 1234G-G4321** [comment]
Send screenshots of
- game folder
- Cleo folder
- cleo\cleo_plugins folder

**Comment by 1234G-G4321** [comment]
Send screenshots of
- game folder
- Cleo folder
- cleo\cleo_plugins folder

also install NewOpcodes.cleo and try
https://www.mixmods.com.br/2020/10/newopcodes-cleo-v2-1/
