### ISSUE TITLE
not working with Skin Selector 2.1 (Modloader version)

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO5#60]
https://www.mixmods.com.br/2015/09/skin-selector-v2-1-ml-e-v2-1-c/

results in 

![fm92li](https://github.com/cleolibrary/CLEO5/assets/5698288/335dbbda-9036-47f4-a307-27521e4e3d0a)

**Comment by ejp2001** [comment]
Mod fails to load saved player model at game startup. Two entries appear in selector list: "$FASTMAN92LI". Clicking either link results in: Unhandled exception at 0x6BF242BD in std.stream.dll (+0x342bd): 0xC0000005: Access violation reading location 0x00000000. Force close via task manager.

Including logs from last run:

[cleo.log](https://github.com/cleolibrary/CLEO5/files/14336811/cleo.log)
[cleo_redux.log](https://github.com/cleolibrary/CLEO5/files/14336812/cleo_redux.log)
[fastman92limitAdjuster.log](https://github.com/cleolibrary/CLEO5/files/14336813/fastman92limitAdjuster.log)
[gta_sa.exe_2024-02-19_15-49-30.log](https://github.com/cleolibrary/CLEO5/files/14336814/gta_sa.exe_2024-02-19_15-49-30.log)

**Comment by ejp2001** [comment]
Second .cleo log didn't upload with first, so I renamed.
[CLEOcleo.log](https://github.com/cleolibrary/CLEO5/files/14336837/CLEOcleo.log)

**Comment by MiranDMC** [comment]
`CLEOcleo.log` look very weird. Several default Cleo's plugins not registered any opcodes at all.

**Comment by x87** [comment]
Those must CLEO Redux plugins

**Comment by MiranDMC** [comment]
Looks like another plugins collision. Now regular Cleo also has MemoryOperations plugin.

**Comment by MiranDMC** [comment]
Mostly fixed in alpha.46
There is still issue with ModLoader, causing addon skins to be not listed in menu.

**Comment by x87** [comment]
@ejp2001 can you try this mod with alpha.70? does it work?

**Comment by ejp2001** [comment]
Skin Selector (c) doesn't save the character (could be one of my scripts). But everything else seems to work ok.

**Comment by ejp2001** [comment]
Save file is created in cleo_saves folder, but game is not loading it. I disabled all of my scripts to make sure it wasn't anything on my end.

**Comment by MiranDMC** [comment]
@ejp2001 can you give link to your Skin Selector? I'm looking at sources and I do not see any thing related to save files.

**Comment by ejp2001** [comment]
It'd the MixMods Modloader version... https://www.mixmods.com.br/2015/09/skin-selector-v2-1-ml-e-v2-1-c/. I rarely use it anymore.

**Comment by MiranDMC** [comment]
@ejp2001 Which version? I used N variant before. When files are saved and what is the result then?

**Comment by ejp2001** [comment]
(c) version is the one that saves the player model for next load. Everything else works but that.

**Comment by ejp2001** [comment]
That WAS one of the main reasons I used it, until I decided I could do more with separate player folders. I still like it for building peds, because I don't have to register them. But I can use any version for that.

**Comment by MiranDMC** [comment]
Downloaded skin models work in Alpha.75
State loading still not functional.

**Comment by x87** [comment]
How is the state saving/loading done in this script? Can someone show the source?

**Comment by MiranDMC** [comment]
[skin_c.txt](https://github.com/user-attachments/files/17274227/skin_c.txt)
It is done via CLEO thread saving feature.
I can see the save file is created and loaded, data detected. Thread is correctly identified and saved state seems to be applied.
