### ISSUE TITLE
not working with Simple Free Cam v2.1.1 (free camera)

### ISSUE THREAD

**Issue by x87** [cleolibrary/CLEO5#64]
https://www.mixmods.com.br/2021/12/simple-free-cam-camera-livre/

**Comment by johnnie-br** [comment]
👀

**Comment by x87** [comment]
it works for me on alpha.35

@johnnie-br please confirm

**Comment by johnnie-br** [comment]
> it works for me on alpha.35
> 
> @johnnie-br please confirm

Ok, I go to confirm

**Comment by MiranDMC** [comment]
Ok what exactly the problem is?
It seems to work fine on alpha 45
Menu po pout appears after pressing K+M, mouse controls the camera, control keys works etc.

**Comment by x87** [comment]
confirmed to work on .46
